version: '3.8'

services:
  backend:
    build: ./server
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

  frontend:
    build: ./client
    ports:
      - 8080:8080
    command: npm run serve